# Generated by Django 2.0.5 on 2018-05-03 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Describe what needs to be done.', max_length=140, verbose_name='Task Title')),
                ('description', models.TextField(help_text='Explain what needs to be done. How will it help? How should people interested in helping contact you or get involved?', max_length=600, verbose_name='Description')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Cause')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
