# Generated by Django 2.0.5 on 2018-05-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180502_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercause',
            name='description',
            field=models.TextField(
                blank=True,
                help_text=
                'Describe your involvement. How have you been involved? What have you done? What would you like to do? You may Include links.',
                max_length=300,
                verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='usercause',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='causes',
                related_query_name='cause',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='description',
            field=models.TextField(
                blank=True,
                help_text=
                'Describe your involvement. How have you been involved? What have you done? What would you like to do? You may Include links.',
                max_length=300,
                verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='skills',
                related_query_name='skill',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
