# Generated by Django 2.0.5 on 2018-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180503_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(
                default=False,
                help_text=
                'Only logged in users can view your profile and tasks by default. If enabled, anyone can view your profile and tasks.',
                verbose_name='Viewable by public internet'),
        ),
    ]
